[2024-01-31T22:49:26.238+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: challenger_leaderboard.tft_challenger_rank__2 manual__2024-01-31T22:49:23.578741+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
