[2024-01-30T21:48:15.606+0000] {processor.py:161} INFO - Started process (PID=17486) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:48:15.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:48:15.607+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:48:15.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:48:15.620+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:48:15.619+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:48:15.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:48:15.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.045 seconds
[2024-01-30T21:48:36.529+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:48:36.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:48:36.532+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:48:36.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:48:36.543+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:48:36.541+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:48:36.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:48:36.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.049 seconds
[2024-01-30T21:49:06.700+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:49:06.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:49:06.701+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:49:06.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:49:06.710+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:49:06.709+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:49:06.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:49:06.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.040 seconds
[2024-01-30T21:49:37.115+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:49:37.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:49:37.117+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:49:37.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:49:37.125+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:49:37.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:49:37.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:49:37.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.038 seconds
[2024-01-30T21:50:07.358+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:50:07.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:50:07.360+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:50:07.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:50:07.368+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:50:07.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:50:07.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:50:07.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.040 seconds
[2024-01-30T21:50:37.427+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:50:37.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:50:37.429+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:50:37.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:50:37.438+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:50:37.436+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:50:37.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:50:37.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.042 seconds
[2024-01-30T21:51:07.844+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:51:07.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:51:07.846+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:51:07.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:51:07.855+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:51:07.853+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:51:07.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:51:07.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.041 seconds
[2024-01-30T21:51:47.417+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:51:47.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:51:47.419+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:51:47.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:51:47.429+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:51:47.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:51:47.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:51:47.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.049 seconds
[2024-01-30T21:52:18.118+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:52:18.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:52:18.120+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:52:18.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:52:18.129+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:52:18.127+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:52:18.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:52:18.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.042 seconds
[2024-01-30T21:52:48.518+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:52:48.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:52:48.520+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:52:48.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:52:48.530+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:52:48.528+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:52:48.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:52:48.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.054 seconds
[2024-01-30T21:53:19.082+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:53:19.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:53:19.084+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:53:19.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:53:19.092+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:53:19.090+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:53:19.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:53:19.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.039 seconds
[2024-01-30T21:53:49.316+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:53:49.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:53:49.318+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:53:49.317+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:53:49.328+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:53:49.326+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:53:49.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:53:49.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.046 seconds
[2024-01-30T21:54:19.677+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:54:19.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:54:19.679+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:54:19.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:54:19.688+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:54:19.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 3, in <module>
    from riotwatcher import TftWatcher
ModuleNotFoundError: No module named 'riotwatcher'
[2024-01-30T21:54:19.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:54:19.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.044 seconds
[2024-01-30T21:54:49.985+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:54:49.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:54:49.987+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:54:49.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:54:50.277+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:54:50.275+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 5, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
[2024-01-30T21:54:50.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:54:50.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.321 seconds
[2024-01-30T21:55:20.195+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:55:20.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:55:20.197+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:55:20.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:55:20.374+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:55:20.372+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 5, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
[2024-01-30T21:55:20.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:55:20.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.210 seconds
[2024-01-30T21:55:50.801+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:55:50.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:55:50.803+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:55:50.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:55:51.125+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:55:51.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 5, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
[2024-01-30T21:55:51.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:55:51.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.360 seconds
[2024-01-30T21:56:08.509+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:08.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:56:08.511+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:56:08.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:08.820+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:56:08.817+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 77, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:56:08.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:08.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.343 seconds
[2024-01-30T21:56:26.768+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:26.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:56:26.769+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:56:26.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:26.959+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:56:26.956+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 77, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:56:26.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:26.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.227 seconds
[2024-01-30T21:56:57.709+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:57.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:56:57.710+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:56:57.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:57.994+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:56:57.992+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 77, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:56:57.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:56:58.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.313 seconds
[2024-01-30T21:57:16.357+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:16.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:57:16.359+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:57:16.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:16.646+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:57:16.644+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:57:16.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:16.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.317 seconds
[2024-01-30T21:57:46.797+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:46.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:57:46.798+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:57:46.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:47.065+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:57:47.063+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:57:47.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:47.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.297 seconds
[2024-01-30T21:57:51.120+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:51.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:57:51.121+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:57:51.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:51.407+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:57:51.404+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:57:51.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:57:51.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.318 seconds
[2024-01-30T21:58:21.841+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:58:21.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:58:21.842+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:58:21.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:58:22.126+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:58:22.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:58:22.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:58:22.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.314 seconds
[2024-01-30T21:58:52.629+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:58:52.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:58:52.630+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:58:52.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:58:52.905+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:58:52.902+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:58:52.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:58:52.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.308 seconds
[2024-01-30T21:59:23.440+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:59:23.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:59:23.442+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:59:23.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:59:23.740+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:59:23.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:59:23.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:59:23.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.329 seconds
[2024-01-30T21:59:54.154+0000] {processor.py:161} INFO - Started process (PID=473) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:59:54.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T21:59:54.157+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:59:54.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:59:54.453+0000] {logging_mixin.py:188} INFO - [2024-01-30T21:59:54.451+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T21:59:54.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T21:59:54.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.337 seconds
[2024-01-30T22:00:24.786+0000] {processor.py:161} INFO - Started process (PID=532) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:00:24.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:00:24.787+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:00:24.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:00:25.052+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:00:25.049+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:00:25.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:00:25.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.303 seconds
[2024-01-30T22:01:04.104+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:01:04.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:01:04.105+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:01:04.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:01:04.293+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:01:04.290+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:01:04.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:01:04.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.218 seconds
[2024-01-30T22:01:34.906+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:01:34.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:01:34.907+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:01:34.907+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:01:35.202+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:01:35.200+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:01:35.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:01:35.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.325 seconds
[2024-01-30T22:02:05.617+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:02:05.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:02:05.619+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:02:05.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:02:05.898+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:02:05.896+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:02:05.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:02:05.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.318 seconds
[2024-01-30T22:02:36.471+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:02:36.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:02:36.472+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:02:36.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:02:36.775+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:02:36.773+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:02:36.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:02:36.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.335 seconds
[2024-01-30T22:03:07.097+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:07.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:03:07.098+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:07.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:07.436+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:07.434+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:03:07.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:07.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.374 seconds
[2024-01-30T22:03:37.946+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:37.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:03:37.947+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:37.947+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:38.239+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:38.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:03:38.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:38.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.322 seconds
[2024-01-30T22:03:44.510+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:44.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:03:44.511+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:44.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:44.778+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:44.776+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_dag = tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:03:44.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:44.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.297 seconds
[2024-01-30T22:03:45.660+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:45.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:03:45.661+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:45.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:45.967+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:03:45.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_dag = tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:03:45.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:03:45.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.339 seconds
[2024-01-30T22:04:22.532+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:04:22.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:04:22.534+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:04:22.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:04:22.710+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:04:22.706+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_dag = tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:04:22.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:04:22.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.226 seconds
[2024-01-30T22:04:53.142+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:04:53.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:04:53.143+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:04:53.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:04:53.423+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:04:53.421+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/tft_sp_stats.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tft_sp_stats.py", line 78, in <module>
    tft_dag = tft_pipeline()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3895, in factory
    dag_id or f.__name__,
AttributeError: '_TaskDecorator' object has no attribute '__name__'
[2024-01-30T22:04:53.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:04:53.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 0.317 seconds
[2024-01-30T22:05:10.444+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:05:10.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:05:10.446+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:10.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:05:10.959+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:10.958+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:05:10.959+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:10.959+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:05:10.959+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:10.959+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2024-01-30T22:05:11.126+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:11.126+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:05:11.126+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:11.126+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:05:11.127+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:11.126+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 400/10s
[2024-01-30T22:05:11.230+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:11.230+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 200/10s
[2024-01-30T22:05:13.769+0000] {logging_mixin.py:188} INFO - augments     object
placement     int64
units        object
level         int64
dtype: object
[2024-01-30T22:05:13.933+0000] {processor.py:840} INFO - DAG(s) 'tft_pipeline' retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:05:14.005+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:14.005+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:tft_pipeline
[2024-01-30T22:05:14.012+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:14.012+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:tft_pipeline
[2024-01-30T22:05:14.017+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:14.017+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:tft_pipeline
[2024-01-30T22:05:14.018+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:14.018+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T22:05:14.027+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:14.027+0000] {dag.py:3058} INFO - Creating ORM DAG for tft_pipeline
[2024-01-30T22:05:14.036+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:14.036+0000] {dag.py:3823} INFO - Setting next_dagrun for tft_pipeline to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T22:05:14.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 3.614 seconds
[2024-01-30T22:05:35.720+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:05:35.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:05:35.722+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:35.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:05:36.030+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.030+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:05:36.030+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.030+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:05:36.031+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.031+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2024-01-30T22:05:36.195+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.195+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:05:36.195+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.195+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:05:36.196+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.195+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 400/10s
[2024-01-30T22:05:36.347+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:36.347+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 200/10s
[2024-01-30T22:05:38.163+0000] {logging_mixin.py:188} INFO - augments     object
placement     int64
units        object
level         int64
dtype: object
[2024-01-30T22:05:38.349+0000] {processor.py:840} INFO - DAG(s) 'tft_pipeline' retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:05:38.545+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:38.545+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T22:05:38.560+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:05:38.560+0000] {dag.py:3823} INFO - Setting next_dagrun for tft_pipeline to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T22:05:38.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 2.861 seconds
[2024-01-30T22:06:08.712+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:06:08.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:06:08.713+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:08.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:06:09.156+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.156+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:06:09.156+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.156+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:06:09.157+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.157+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2024-01-30T22:06:09.304+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.304+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:06:09.304+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.304+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:06:09.305+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.304+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 400/10s
[2024-01-30T22:06:09.369+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:09.369+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 200/10s
[2024-01-30T22:06:10.980+0000] {logging_mixin.py:188} INFO - augments     object
placement     int64
units        object
level         int64
dtype: object
[2024-01-30T22:06:11.068+0000] {processor.py:840} INFO - DAG(s) 'tft_pipeline' retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:06:11.089+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:11.089+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T22:06:11.107+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:11.107+0000] {dag.py:3823} INFO - Setting next_dagrun for tft_pipeline to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T22:06:11.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 2.414 seconds
[2024-01-30T22:06:41.426+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:06:41.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/tft_sp_stats.py for tasks to queue
[2024-01-30T22:06:41.428+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:41.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:06:41.905+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:41.904+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:06:41.905+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:41.905+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:06:41.906+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:41.905+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2024-01-30T22:06:42.068+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:42.068+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2024-01-30T22:06:42.069+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:42.068+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2024-01-30T22:06:42.069+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:42.069+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 400/10s
[2024-01-30T22:06:42.140+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:42.140+0000] {Limits.py:87} INFO - rate limit changed from 0/0s to 200/10s
[2024-01-30T22:06:44.167+0000] {logging_mixin.py:188} INFO - augments     object
placement     int64
units        object
level         int64
dtype: object
[2024-01-30T22:06:44.303+0000] {processor.py:840} INFO - DAG(s) 'tft_pipeline' retrieved from /opt/airflow/dags/tft_sp_stats.py
[2024-01-30T22:06:44.330+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:44.330+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-30T22:06:44.348+0000] {logging_mixin.py:188} INFO - [2024-01-30T22:06:44.348+0000] {dag.py:3823} INFO - Setting next_dagrun for tft_pipeline to 2024-01-30 00:00:00+00:00, run_after=2024-01-31 00:00:00+00:00
[2024-01-30T22:06:44.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/tft_sp_stats.py took 2.939 seconds
