[2024-02-02T16:07:54.069+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: challenger_leaderboard.tft_challenger_rank manual__2024-02-02T16:07:53.008318+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
